// This file is generated by Slice Machine. Update with care!

import Grupo from './Grupo';
import Tabela from './Tabela';
import Time from './Time';

export {
	Grupo,
	Tabela,
	Time,
};

export const components = {
	grupo: Grupo,
	tabela: Tabela,
	time: Time,
};
